name: Build APK

# Trigger the workflow on push or pull request to main branch
on:
  push:
    branches:
      - master  # You can replace "main" with the name of your branch (e.g., "master")
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the repository
    - name: Checkout code
      uses: actions/checkout@v2

    # Step 2: Set up Java JDK (required for Android builds)
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'

    # Step 3: Set up Android SDK
    - name: Set up Android SDK
      uses: reactivecircus/android-sdk-manager-action@v2
      with:
        api-level: 30    # Set this to the target API level for your project
        build-tools: 30.0.3  # Set the required build tools version for your project
        cache: true

    # Step 4: Gradle Build (using the Gradle Wrapper)
    - name: Build APK with Gradle
      run: ./gradlew assembleRelease

    # Step 5: Upload APK as an artifact (optional, if you want to download it)
    - name: Upload APK
      uses: actions/upload-artifact@v2
      with:
        name: app-release
        path: app/build/outputs/apk/release/app-release.apk
