name: Build APK

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK 17 (Temurin)
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Set up Android SDK
      run: |
        # Install necessary dependencies
        sudo apt update
        sudo apt install -y openjdk-17-jdk wget unzip

        # Define SDK path
        export ANDROID_SDK_ROOT=$HOME/android-sdk

        # Create Android SDK directory
        mkdir -p $ANDROID_SDK_ROOT

        # Download command line tools (latest version)
        wget https://dl.google.com/android/repository/commandlinetools-linux-9477386_latest.zip -P $ANDROID_SDK_ROOT

        # Unzip the command line tools into the SDK directory
        unzip $ANDROID_SDK_ROOT/commandlinetools-linux-9477386_latest.zip -d $ANDROID_SDK_ROOT

        # Rename extracted folder to 'latest'
        mv $ANDROID_SDK_ROOT/cmdline-tools $ANDROID_SDK_ROOT/cmdline-tools/latest

        # Accept licenses and install necessary SDK packages
        yes | $ANDROID_SDK_ROOT/cmdline-tools/latest/bin/sdkmanager --licenses
        $ANDROID_SDK_ROOT/cmdline-tools/latest/bin/sdkmanager "platform-tools" "build-tools;30.0.3" "platforms;android-30"

    - name: Build APK with Gradle
      run: ./gradlew assembleRelease

    - name: Upload APK as an artifact
      uses: actions/upload-artifact@v4
      with:
        name: app-release
        path: app/build/outputs/apk/release/app-release.apk
