name: Build APK

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK 17 (Temurin)
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle

    - name: Set up Android SDK
      uses: android-actions/setup-android@v2
      with:
        api-level: 34
        build-tools: 34.0.0
        target-arch: x86_64

    - name: Check for gradlew file
      run: |
        ls -alh gradlew  # Check if gradlew exists and is executable
        chmod +x gradlew

    - name: Build APK with Gradle
      run: ./gradlew assembleDebug --warning-mode all --stacktrace --info

    - name: Upload APK as an artifact
      uses: actions/upload-artifact@v4
      with:
        name: Tirex Charger
        path: app/build/outputs/apk/debug/app-debug.apk
